### ISSUE TITLE
Get Documents not wrapping LinkInstances causing ArgumentExceptions with nodes expecting wrapped Elements

### ISSUE THREAD

**Issue by ThomasMahon** [ksobon/archilab#11]
A number of BimorphNodes users have reported an ArgumentException with the BimorphNode LinkElement.OfCategory node which is caused by the Archilab Get Documents node. Its returning the raw Revit API object instead of the wrapped Dynamo element. Can you publish an update?

![image](https://user-images.githubusercontent.com/18601851/39448651-7bfe3070-4cbd-11e8-8a16-3d837bb415d7.png)

OOTB nodes:
![image](https://user-images.githubusercontent.com/18601851/39448674-8db8b7ea-4cbd-11e8-899f-cdeaef1f7fe1.png)

**Comment by ksobon** [comment]
@ThomasMahon this should do the trick: 

![image](https://user-images.githubusercontent.com/529781/57186217-fb3ab300-6ea8-11e9-8808-4ad88aa60d60.png)

You can get that by downloading the latest package version: 

![image](https://user-images.githubusercontent.com/529781/57186262-04784f80-6eaa-11e9-88e0-36f1283441f8.png)

**Comment by ThomasMahon** [comment]
Cheers mate.
