### ISSUE TITLE
Views.SetWorksetVisibility

### ISSUE THREAD

**Issue by PeterCh84** [ksobon/archilab#118]
I wanted to work with Views.SetWorksetVisibility, but it seems to be missing in Dynamo for Revit 2023. Is that correct? I was trying to create my own node with Python code, but with no luck. If possible, could this node be recreated? Thank you.

**Comment by ksobon** [comment]
@PeterCh84 which version of archi-lab do you have installed?

**Comment by PeterCh84** [comment]
I take it back. I had to remove previous version and install it back again and now I see it is there. Sorry. All good. Thanks
