### ISSUE TITLE
ViewType going Bezerk

### ISSUE THREAD

**Issue by DanielHurtubise** [ksobon/archilab#23]
![image](https://user-images.githubusercontent.com/4299930/47780067-e8c59e00-dcfa-11e8-8b92-f582418758d1.png)

After closing and reopening it adds another output :)

**Comment by ksobon** [comment]
What version of Revit, Dynamo, and archi-lab.net do you have installed? This happens if you are on an old version of the package. If I remember correctly the latest is 2019.2.6.

**Comment by DanielHurtubise** [comment]
Revit 2019.1
Dynamo 2.0.1.5065
archi 2018.13.13

Guess im going to upgrade :)
