### ISSUE TITLE
annotation tag node needs a little love

### ISSUE THREAD

**Issue by ksobon** [ksobon/archilab#24]
https://forum.dynamobim.com/t/trouble-with-creating-annotations/28113

**Comment by andydandy74** [comment]
Hey Konrad, while you're at it, could you replace line 79 of the Python script with
```
if tagType.Category.Id == ElementId(BuiltInCategory.OST_RoomTags):
```
and line 101 with
```
elif tagType.Category.Id == ElementId(BuiltInCategory.OST_MEPSpaceTags):
```
to make the node work under non-English Revit UI as well?

**Comment by richschmitt** [comment]
a few notes on this @ksobon: for revit 2019 they removed the Document.Create.NewTag method, and they suggest IndependentTag.Create which will use the default tag for that category (also requires a bunch of other params) so if you want a different tag, you have to then set the type param to the desired type.

BUT, if you want to tag a room, area or other spatial element... there is currently no method for this in the API.  There is supposed to be a SpatialElementTag.Create method, but either does not exist or is not exposed in the API
