### ISSUE TITLE
Dropdown List Selector Crashes Revit

### ISSUE THREAD

**Issue by shnlmn** [ksobon/archilab#31]
The list selector components are crashing Revit. I'm using Revit 2019.0.2 and Archi-Lab 2019.2.11.

As seen below, the component will list the options, but checking any of them will cause a crash.

<img src="https://i.imgur.com/UwSmCOf.png" />

**Comment by ksobon** [comment]
![image](https://user-images.githubusercontent.com/529781/52023114-dc9fd700-24c9-11e9-881a-adaf18b6ed94.png)

Should be good now. Try this version: 

![image](https://user-images.githubusercontent.com/529781/52023181-1a046480-24ca-11e9-8c49-ff451ec365c4.png)
