### ISSUE TITLE
Tag Host Element

### ISSUE THREAD

**Issue by DanielHurtubise** [ksobon/archilab#32]
Im passing a list of  RoomTag to this node and im getting this error
![image](https://user-images.githubusercontent.com/4299930/51239754-7750cf80-197a-11e9-9e3b-c375d30afbce.png)

Thanks for the help... and the package ;)

**Comment by ksobon** [comment]
Can you flatten it?

**Comment by ksobon** [comment]
@DanielHurtubise is this still an issue? Can you just flatten it, or are you looking for a change so that the node works with any depth of a list?

**Comment by DanielHurtubise** [comment]
Morning Konrad,
sorry about that. II get the same results using the flatten. 
![tag host elements](https://user-images.githubusercontent.com/4299930/52040291-37234c80-2537-11e9-8250-35673ef38028.png)

**Comment by DanielHurtubise** [comment]
And yes any List depth would be great anyways :)

**Comment by ksobon** [comment]
OK, try this: 

![image](https://user-images.githubusercontent.com/529781/52058314-325d9900-2535-11e9-85f1-1a86e7aff650.png)

Please download the latest version of archi-lab: 

![image](https://user-images.githubusercontent.com/529781/52058427-65079180-2535-11e9-8b5f-38a6df670413.png)
