### ISSUE TITLE
Get ViewFamily Type

### ISSUE THREAD

**Issue by mrainville1618** [ksobon/archilab#33]
Modified the Get Viewport Type node. This allowed me to obtain a list of ViewFamily Types and is useful for my process in initial project setup.
I was unable to figure out the Pull Request as there only seemed to be the one Master branch.

# Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net
# Edited to get viewfamilytypes by @Mark0Rainville

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

try:
	errorReport = None
        #Revised this section to select the higher level elements of the class ViewFamilyType
	viewfamilies = FilteredElementCollector(doc).OfClass(ViewFamilyType).ToElements()
	
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
#Changed OUTput to the viewfamilies variable
	OUT = viewfamilies
else:
	OUT = errorReport

**Comment by ksobon** [comment]
@mrainville1618 I think your custom node functionality can be achieved using OOTB nodes like so: 

![image](https://user-images.githubusercontent.com/529781/57197500-fb34c480-6f35-11e9-94fe-0a952a71a197.png)

I will not be implementing this code. Thanks!

**Comment by mrainville1618** [comment]
Yes, I found that not too long after. Thanks for the follow up.
- Mark
