### ISSUE TITLE
Get Worksets

### ISSUE THREAD

**Issue by DanielHurtubise** [ksobon/archilab#35]
I pasted the code into a Python node and i'm getting an error at line 33

Traceback (most recent call last):
File "<string>", line 33, in <module?
TypeError: expected Document, got list

**Comment by ksobon** [comment]
I think this can be achieved with this node now: 

![image](https://user-images.githubusercontent.com/529781/52018482-92fac080-24b8-11e9-9d16-50aa5308f81f.png)
