### ISSUE TITLE
Set BuiltIn Parameter improvement suggestion

### ISSUE THREAD

**Issue by Thomas84** [ksobon/archilab#38]
Would be great if the ParameterValues input checks, if the input is a list, if not create a list automatically. U could change then the input name to: ParameterValue(s)
What do u think?

![29-01-_2019_15-20-21](https://user-images.githubusercontent.com/5624034/51914670-aedb6500-23d9-11e9-8135-2394bfe4c3e2.png)
![29-01-_2019_15-20-06](https://user-images.githubusercontent.com/5624034/51914677-b13dbf00-23d9-11e9-9396-c7750ff16c66.png)

**Comment by ksobon** [comment]
Have a look at this version: 

![image](https://user-images.githubusercontent.com/529781/51929730-e987d200-23c6-11e9-9961-11f670c70bbf.png)

**Comment by Thomas84** [comment]
ty, that was fast =) it works now without list.create, but the node still show the same error message

**Comment by ksobon** [comment]
@Thomas84 I don't understand. Does it work, or not?

**Comment by Thomas84** [comment]
I don't know why, yesterday I have updated the package with the package manager, and I got the same error message. Today, I have installed the package manually new, and it works everything fine (exactly the same script).
