### ISSUE TITLE
View.Duplicate taking Area Plans

### ISSUE THREAD

**Issue by Vanman989** [ksobon/archilab#39]
Hi, sorry I'm not sure where to post here. If View.Duplicate could take area plans. That would be awesome :) 
![image](https://user-images.githubusercontent.com/25638713/51936050-38d40e00-246c-11e9-9f31-1fc56f7207f4.png)

**Comment by ksobon** [comment]
It works fine with Area Plans: 

![image](https://user-images.githubusercontent.com/529781/52018419-58912380-24b8-11e9-8e91-74fe72ebf847.png)

You have an empty list that you are feeding into the view input, and that's causing the issue. I think that's all Dynamo nodes in general.

**Comment by Vanman989** [comment]
It might be that I need to convert a ViewPlan to AreaPlanView. Would the Views.GetByType node do this? What package is it from?

![image](https://user-images.githubusercontent.com/25638713/52018965-1f58c200-2551-11e9-8620-33524a5f7160.png)
![image](https://user-images.githubusercontent.com/25638713/52018971-25e73980-2551-11e9-8095-0c13367c6311.png)
