### ISSUE TITLE
Missing .dll

### ISSUE THREAD

**Issue by wynged** [ksobon/archilab#4]
the archilab package has some new excel nodes, which look interesting.  unfortunately there is a .dll dependancy that is missing.  Looks like you're using FastMember.Signed for something (reflection?)... but it is not included in the dynamo package.  I downloaded it manually from here [FastMember Nuget](https://www.nuget.org/packages/FastMember.Signed/1.1.0) and put it in my package folder, but it should be in the dynamo package by default.
![missing_fast](https://user-images.githubusercontent.com/5872187/34531323-e568cf74-f07f-11e7-9d8b-463c9e1a6740.png)

**Comment by ksobon** [comment]
@wynged thanks for catching it. It was added in the latest release. 2018.0.9 and will be posted as soon as Package Manager is back up online.
