### ISSUE TITLE
Dynamo 2.0 Deleting an Input Toggle node seems to crash Revit

### ISSUE THREAD

**Issue by dimven** [ksobon/archilab#40]
Dynamo 2.0.2 / Revit 2019

I placed an `Input Toggle` node on the graph by accident and then tried to delete it. Revit and Dynamo both froze. Had to kill it from the task manager.

**Comment by dimven** [comment]
Weird, can't seem to reproduce the crash.

**Comment by ksobon** [comment]
@dimven I had issues reported for this node but they were fixed in latest version of archi-lab. They were related to 2.0.X updates in Dynamo.
