### ISSUE TITLE
Schedules on Sheets error

### ISSUE THREAD

**Issue by DanielHurtubise** [ksobon/archilab#42]
Good morning,
i get this error when using the node
![image](https://user-images.githubusercontent.com/4299930/52551388-95281d80-2ddc-11e9-9def-085e0de614c9.png)

I'm running the latest package i promise (2019.2.15)
Thanks

**Comment by ksobon** [comment]
This is quite an old node, so I decided to replace it with a new approach that will work for other views as well. So to get schedules that are on sheet you can do this: 

![image](https://user-images.githubusercontent.com/529781/52904890-137f2800-3200-11e9-94f3-d1412ff7f865.png)

It can obviously be used for other view types like elevations: 

![image](https://user-images.githubusercontent.com/529781/52904897-3a3d5e80-3200-11e9-845c-d249e65585c3.png)

Or even to get all view types in one go: 

![image](https://user-images.githubusercontent.com/529781/52904920-8092bd80-3200-11e9-8232-c93af45044db.png)

Obviously that last one throws an error when you feed it an empty list, but it still seems to be working for all other elements in that sublist: 

![image](https://user-images.githubusercontent.com/529781/52904935-aa4be480-3200-11e9-8d7a-1abebe953fc3.png)

Get the latest archi-lab.net package: 

![image](https://user-images.githubusercontent.com/529781/52904957-f5fe8e00-3200-11e9-8370-ade49bd49f9d.png)
