### ISSUE TITLE
Get Current Revision On Sheet's Numbers

### ISSUE THREAD

**Issue by MarkAckerley** [ksobon/archilab#45]
Hi Konrad,

Just an idea for a new node or 2  if that's ok, I thought you might be interested as you already have great nodes for pulling Revision information.

If you have a sheet with revisions P01, P02, P03, you can't pull those codes with current nodes.

There is a method in the API for this http://www.revitapidocs.com/2018/f46d2d49-1d37-6e99-f450-d21401fd848f.htm

For me, revisions will be set by Sheet, this can be called as so...
![image](https://user-images.githubusercontent.com/41670424/53155716-8ba96d00-35b5-11e9-8e21-3ac3686c9386.png)

So I have a Python script...

```
revisions = UnwrapElement(IN[0])
sheets = UnwrapElement(IN[1])

revs = []
r = []
Output = []

for sheet, revision in zip(sheets, revisions):
    for sht, rev in zip(sheet, revision):
        r = Autodesk.Revit.DB.ViewSheet.GetRevisionNumberOnSheet(sht, rev.Id)        
        Output.append(r)
        

OUT = Output
```

And a graph...
![image](https://user-images.githubusercontent.com/41670424/53155929-0ecac300-35b6-11e9-9ba3-fb567f8d63a8.png)

Hopefully that's of interest.

Thanks for your awesome work.

Mark

**Comment by ksobon** [comment]
@MarkAckerley Thanks for sharing. I added a new node to Archi-lab.net that should do the trick for you: 

![image](https://user-images.githubusercontent.com/529781/57185972-85cce380-6ea4-11e9-9a2b-dcf6968ffe19.png)

You can find it in the following version: 

![image](https://user-images.githubusercontent.com/529781/57186025-bbbe9780-6ea5-11e9-9d98-6db96251b364.png)

**Comment by MarkAckerley** [comment]
Fantastic thanks :)
