### ISSUE TITLE
Hide All Worksets node

### ISSUE THREAD

**Issue by kilkellym** [ksobon/archilab#46]
Hi Konrad. It appears that the "Hide All Worksets" node is not included in the latest version of archilab (2019.2.17). Was this intentional?

**Comment by ksobon** [comment]
I think I never had "Hide All Worksets" node. Can you install earlier version of the package and confirm that it indeed came from my package?

**Comment by ksobon** [comment]
@kilkellym since I am not hearing back from you, I will close this. Feel free to re-open.
