### ISSUE TITLE
ViewSets.ByViewsName Return Modification

### ISSUE THREAD

**Issue by CunninghamL** [ksobon/archilab#50]
I’d like to request a way to return the newly created ViewSet in the ViewSets.ByViewsName Node, opposed or in addition to the boolean value.
![image](https://user-images.githubusercontent.com/49533190/55980874-4bc44500-5c4a-11e9-9673-dc0d0ef797e4.png)
_^Document.Views is from Clockwork_

I’m a little rusty on programming but it might simply look something like this from: https://github.com/ksobon/archilab/blob/master/archilab/Revit/Views/ViewSets.cs
 ![image](https://user-images.githubusercontent.com/49533190/55980888-541c8000-5c4a-11e9-967f-46e6fc7465d3.png)

**Comment by ksobon** [comment]
This should do the trick: 

![image](https://user-images.githubusercontent.com/529781/56179087-7b6ca780-5fd2-11e9-8d9c-e51339c9a0ec.png)

![image](https://user-images.githubusercontent.com/529781/56179636-73ae0280-5fd4-11e9-8883-0bca9b8e41d0.png)

**Comment by CunninghamL** [comment]
Thank you very much. 👍
