### ISSUE TITLE
what version will work for Dynamo 1.3.2 ( Revit 2016)?

### ISSUE THREAD

**Issue by heinrichboldt** [ksobon/archilab#52]
Hello Konrad, 

can you give me info, what version of Archi-lab.net will work with Dynamo 1.3.2. since we have still ongoing projects with Revit 2016.

Thank you a  lot.

**Comment by ksobon** [comment]
So version numbers are tied to versions of Dynamo and Revit. For Dynamo 1.3 look for a version that has XXXX.13.XX structure. First four digits denote Revit version ie. 2020 then Dynamo version 13 = 1.3 and last digits are just build numbers that I bump every time I release an update.

**Comment by heinrichboldt** [comment]
Thank you a lot!
That was not clear for me, sorry for disturbing

Beste regards 
Heinrich
