### ISSUE TITLE
Printing multiple PDF's in multiple sizes failes

### ISSUE THREAD

**Issue by Huffen** [ksobon/archilab#55]
Hi

Different errors appear, see below, and different results is achieved.
Sometimes I get one PDF created, sometimes none.
The issue is only in RVT 2019 and 2020. RVT 2018 works fine.
I have no idea of why it failes in 2019 and 2020, but works fine in 2018.

Following packages is used: Spring, Clockwork, Genius Loci and Archilab.
Setup to script:
![Print PDF](https://user-images.githubusercontent.com/37217361/68367342-d6fcaf00-0135-11ea-9702-ccd178a5b6d7.PNG)

Error 1:
Traceback (most recent call last):
File "string", line 139, in module
Exception: The iterator cannot proceed due to changes made to the Element table in Revit's database
(typically, this can the result of an Element deletion).

Result:
One PDF is printed.

Error 2:
Traceback (most recent call last):
File "string", line 152, in module
File "string", line 130, in PrintView
SystemError: attemted to read or write protected memory. This is often an indication that other memory is corrupt
![Error 2](https://user-images.githubusercontent.com/37217361/68367199-6eadcd80-0135-11ea-80f2-d3602578d78b.PNG)

Result:
One PDF is printed.

Error 3:
Traceback (most recent call last):
File "<string>", line 140, in module
Exception: The iterator cannot proceed due to changes made to the Element table in Revit's database
(typically, this can the result of an Element deletion).

Result:
No PDF is printed.

**Comment by DragonTof** [comment]
Have you found a solution ?
