### ISSUE TITLE
FloorPlan.ByRoom - ViewPlan object has no attribute 'viewName'

### ISSUE THREAD

**Issue by mfleming04** [ksobon/archilab#57]
Info:
Revit 2020.2.1
Dynamo Revit 2.3.0.7661
Dynamo Core 2.3.0.5885
archilab v 2019.2.27

When trying to use the FloorPlan.ByRoom I get error on line 97
AttributeError:  "viewPlan" object has no attribute 'viewName'

It creates the views but does not change the names or crop or anything.
Just a basic square with 3 rooms.

![DynamoError_archilab_1](https://user-images.githubusercontent.com/22360133/75641617-71f62900-5bfe-11ea-9962-5fc646c0f7c5.jpg)
![DynamoError_archilab_2](https://user-images.githubusercontent.com/22360133/75641653-905c2480-5bfe-11ea-8b08-6149f306a734.jpg)

**Comment by ksobon** [comment]
Please update to the latest version of Archi-lab.net and check if that error still persists.

**Comment by ksobon** [comment]
@mfleming04 yeah, that was fixed in newer versions. 

![image](https://user-images.githubusercontent.com/529781/75642069-d960a880-5bff-11ea-92d0-ff78f634890b.png)

![image](https://user-images.githubusercontent.com/529781/75642080-e2517a00-5bff-11ea-9013-02e586f39c45.png)
