### ISSUE TITLE
Relay nodes causing crashes and disconnected strings

### ISSUE THREAD

**Issue by rvida5** [ksobon/archilab#60]
I've been having issues where relay nodes get accidentally created when I don't want them (probably accidentally double clicking near the middle of a string). Then when I try to delete the node and redraw the string between the original nodes it sometimes doesn't get rid of the strings (they stay visible with 1 or 2 unconnected ends). This then leads to crashes sometimes within dynamo and the only way around it is to restart but sometimes it also seems to corrupt the file. It would be good if it were possible to make the relay node feature optional. 

Aside from that, thanks for the awesome package!

Originally posted here: https://forum.dynamobim.com/t/disconnected-strings-cant-be-deleted/51754/7

Software versions:
Revit 2018.3
Dynamo 2.0.3.8810
archi-lab.net 2020.23.13

**Comment by ksobon** [comment]
@rvida5 if you download the latest version of archi-lab.net 

![image](https://user-images.githubusercontent.com/529781/85174731-8e64b280-b23b-11ea-8048-4e358c00cd93.png)

you will only be able to place a relay node via CTRL + Click in the middle of the wire. That should prevent any more accidental placements.
