### ISSUE TITLE
Speller.Speller Node

### ISSUE THREAD

**Issue by ericenagel** [ksobon/archilab#63]
I am receiving the following error while attempting to run a script that contains the Speller.Speller node.  This is being preforming in Revit 2020.2 with Dynamo version 2.3.  I currently have installed the latest version of the Archi-Lab.net package (2021.25.2621).  Also, note that I am using the .dic and .aff files that are linked from the 'Spell Checking w/ Dynamo' posting.

"Warning: Speller..ctor operation failed.  The type initializer for 'WeCantSpell.Hunspell.AffixReader' threw an exception."

Interestingly, I have tested this same node in Revit 2021.1.2 / Dynamo 2.6 with the Archi-Lab.net package (2021.25.21) installed.  Here, the script works as expected...no errors.

Can you please help me figure out what is going on?  Thank you!

**Comment by ksobon** [comment]
@ericenagel this should have been resolved in version 2022.210.1320. Please download that for Revit 2020 and let me know if there still an issue. 

Ps. Please consider supporting archi-lab.net at: https://www.patreon.com/archilab

**Comment by ericenagel** [comment]
Still having issues….

***@***.***D750E0.ABE077B0]

I downloaded and tried the following versions:
2022.210.1322
2022.210.1320

[cid:Logo_CushingTerrell_Sig_c8278f6f-8f3f-45ad-8476-3bbae351291a.png]
[cid:LinkedIn_icon_teal_eab3e198-ada5-4916-b445-7ab6a45a1183.png]       [cid:Twitter_icon_teal_7116b3e6-4583-4d6e-8764-aaf20e227c84.png]        [cid:Instagram_icon_teal_231c6090-3632-4fca-844f-5c96ef34c32f.png]      [cid:Facebook_icon_teal_7dd3ce24-c562-45c4-b38a-2f74c2be7031.png]


Eric Nagel
BIM Coordinator
[cid:Phone_icon_teal_ec4e89bf-1bf7-4941-9490-c24b3fe13977.png]  512.872.3019<tel:512.872.3019>  [cid:Website_icon_teal_c1c2bcac-4de5-47f3-b080-9309a44f8ab4.png]        cushingterrell.com<http://www.cushingterrell.com/>

CTA is now Cushing Terrell.

**Comment by ksobon** [comment]
Just uploaded new version that will have the System.Buffers that was missing. 2022.210.1420
