### ISSUE TITLE
Newer Version Compatibility with Dynamo 2.0.4

### ISSUE THREAD

**Issue by BJozi** [ksobon/archilab#64]
I'm updating packages and currently on an older version (2019.2.27), is the latest version (2021.25.2721) compatible with Dynamo V2.0.4 and Revit 2019?

I know from other packages, typically it's ok if there are no API related changes to update/use the most current version.

**Comment by ksobon** [comment]
Yeah, give it a try. I don't know from top of my head. There are about a dozen different versions of Dynamo out there. Try it out, and let me know if you see any issues.
