### ISSUE TITLE
Views.CreateCallout node

### ISSUE THREAD

**Issue by MTJ001** [ksobon/archilab#65]
Hello Konrad,

I have noticed that the Views.CreateCallout node just works when used in an Arch. floor plan. I just wonder if it is an API limitation within this archi-lab version and will be implemented for str. floor plans in the future versions. See below dynamo forum thread about it.
I'm currently using Dynamo 2.3.0 with RVT 2020.2 and archi-lab 2020.23.1

[https://forum.dynamobim.com/t/specified-argument-was-out-of-range-of-valid-values/64175](url)

Regards

Mario

**Comment by ksobon** [comment]
@MTJ001 please download 2022.210.1520 and let me know if this is still an issue.
