### ISSUE TITLE
Latest version does not load in Revit 2022

### ISSUE THREAD

**Issue by vinnividivicci** [ksobon/archilab#66]
Hello,

First of all, thanks for your excellent work on this package.

Installing it in Revit 2022 does not seem to work.

I installed this version:
![image](https://user-images.githubusercontent.com/591242/119667481-55966b80-be04-11eb-8557-0ece397cc99e.png)

Nothing shows up:
![image](https://user-images.githubusercontent.com/591242/119667537-60510080-be04-11eb-9400-a2df782e023c.png)

It did get installed into the folder though:
![image](https://user-images.githubusercontent.com/591242/119667604-71017680-be04-11eb-9eb4-989d6f1e2161.png)

Tried disabling pyRevit and removing some other packages but nothing has worked so far.

Thanks for looking into this.

**Comment by ksobon** [comment]
@vinnividivicci for Revit 2022 you want to install the version that ends with "22". 

![image](https://user-images.githubusercontent.com/529781/119682855-d5263980-be08-11eb-8618-21d474d1ea34.png)

**Comment by vinnividivicci** [comment]
@ksobon Thanks for clarifying that and for the quick response!
