### ISSUE TITLE
Update View.HideElements and View.UnhideElements code

### ISSUE THREAD

**Issue by vinnividivicci** [ksobon/archilab#67]
Thank you very much for your very useful dynamo package!

The updated code listed [here ](https://forum.dynamobim.com/t/hide-and-unhide-elements-in-view/29825/5) is working fine for me in Revit 2020 and Revit 2022, but is not included in the latest updates of archi-lab, so one must manually update the custom node after each updated release. 

Would it be possible to include this updated code in the next release please?

**Comment by ksobon** [comment]
@vinnividivicci I got these nodes incorporated into Archi-lab.net Visual Studio project. I removed the DYF files and from now on you should always be able to get the latest code. Please look for these nodes: 

![image](https://user-images.githubusercontent.com/529781/122585506-306ed480-d021-11eb-8316-86984202e8ad.png)
