### ISSUE TITLE
Spell Check doesn't work for Revit 2019

### ISSUE THREAD

**Issue by Kulkul7536** [ksobon/archilab#68]
Hi Konrad,

Spell check throws exception "Operation Failed the type intializer for WeCantSpellAffixReader" in Dynamo 2.0.4.

**Comment by ksobon** [comment]
@Kulkul7536 should be working well now. 

![image](https://user-images.githubusercontent.com/529781/122585783-7cba1480-d021-11eb-8e4f-dca4cc74e773.png)

Ps. Please consider supporting archi-lab.net via Patreon: https://www.patreon.com/archilab
