### ISSUE TITLE
Select.GetDocuments Node

### ISSUE THREAD

**Issue by dazza1639** [ksobon/archilab#69]
I am having trouble with the Select.GetDocuments node on Dynamo 2.0.3 for Revit 2019. When I used the install the latest version install option from the package manager, the Select.GetDocuments node was unrecognised and broke my script. In the end I had to uninstall the Archi-Labs package and install version 2020.23.9 which restored the node. Has Select.GetDocuments been removed from the newer versions of the package? If so, do you know of a similar method to achieve the results provided by this node.

Thanks of all your hard work and great dynamo packages.

Darren

**Comment by ksobon** [comment]
@dazza1639 it's working just fine. I don't see an issue. 

![image](https://user-images.githubusercontent.com/529781/125006025-c3989a00-e022-11eb-88ae-7c358e87a5c2.png)
