### ISSUE TITLE
Create Annotation Tag node does'nt work in localize Revit

### ISSUE THREAD

**Issue by DanielHurtubise** [ksobon/archilab#70]
When looking for the Tag Category the node is using ENU

if tagType.Category.Name == "ENU"
Overwriting the ENU value  with the localized version fixes it (FRA) in my example.

**Comment by ksobon** [comment]
@DanielHurtubise I just published a new version that solves this issue. 

![image](https://user-images.githubusercontent.com/529781/129923346-fb83a2c5-288b-4d38-a31c-b4a852d3f5d3.png)

Please consider supporting archi-lab.net via Patreon: https://www.patreon.com/archilab
