### ISSUE TITLE
Select.GetRoomatpoint error

### ISSUE THREAD

**Issue by rizzoblo** [ksobon/archilab#84]
Select.GetRoomatpoint is throwing an error (See Image).  Using the latest version 2022.212.2722  Revit Version is the latest 22.1.1.516
20210921_1515(x64)
2022.1

![archilab](https://user-images.githubusercontent.com/49462811/138958232-29f76e7e-af1a-494a-b100-77ffba071ed1.png)

**Comment by ksobon** [comment]
@rizzoblo I will close this since I didn't hear from you with a sample file to re-create this issue.
