### ISSUE TITLE
Relay copy

### ISSUE THREAD

**Issue by Konrad-X-PLAN** [ksobon/archilab#85]
When I try to copy&paste nodes with relay it becomes "deprecated".

![relay_copy](https://user-images.githubusercontent.com/56676003/143149779-59d1d645-5063-4a24-8dbf-740168502489.gif)

my configuration:
![image](https://user-images.githubusercontent.com/56676003/143149884-7ec669e8-f410-4d4a-b32f-d864ce6f0990.png)

**Comment by ksobon** [comment]
@Konrad-X-PLAN the latest version of Dynamo seems to have a pin node like this, so I will be deprecating/removing this as soon as the other one gets released. Thanks for reporting this.
