### ISSUE TITLE
Archi-lab.net not working on Dynamo 2.12

### ISSUE THREAD

**Issue by Juvenciodas** [ksobon/archilab#88]
I have tried installing multiple versions of Archi-lab.net on Dynamo 2.12, with no success.
I can force Dynamo to read the Archi-lab.net package but it will only read the dyf nodes.

Any advice or suggestions.
I have rebuilt most of my scripts so that they do not include any Archi-lab.net nodes, but this becomes tedious to do, as some nodes don't have alternatives.

![2021-08-04 17_16_17-Basalt-4thAugust-2 jpg _ Chris Parker Photographics - Brave](https://user-images.githubusercontent.com/13451452/160305016-82391c9c-ec37-484c-9257-1b2a0af6e90f.png)
.

**Comment by ksobon** [comment]
The version of archi-lab.net that works with Revit 2022 will end in "22". Currently the latest is 2022.212.32**22**.

**Comment by Juvenciodas** [comment]
Thank you @ksobon, success. mental note to self last 2 digits are the version of Revit to use it on.
